### ISSUE TITLE
Config - Add user and password for Admin section

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/api_gateway#71]
Example (rest.admin):
```yaml
rest:
  host: localhost
  port: 5566
  admin:
      user: test_user
      password: Admin1234
  cors:
    enabled: true
  auth:
      enabled: true
      host: localhost
      port: 55909
      path: /auth
      services:
          - name: token
          - name: credentials
      default: token
      endpoints:
          - url: "*://*/merchants/*"
            methods:
          - url: "*://*/categories/*"
            methods:
                - GET
          - url: "*://test_2/*"
            methods:
                - GET
                - PUT
                - POST
          - url: "*://test_1/order*"
            methods:
                - GET
discovery:
  host: localhost
  port: 5567
```
